package com.maths;

public class Exception_Task {
	
		private void method1() {
	
	
		
			try {
				int a=3/0;
				System.out.println(a);
			} catch (ArithmeticException e) {
				e.printStackTrace();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
			
		
		
	

	}
		
		private void method2() {
			
			
			
		}
		
public static void main(String[] args) {

}
}

