package com.maths;

public class Exception_Task {
	//single try with multiple catch
		private static void method1() throws ArithmeticException {
			try {
				int a=3/0;
				System.out.println(a);
			}
			 catch (Exception e1) {
				e1.printStackTrace();
			 }
			finally {
				System.out.println("Ignore Exception");
			}
		}
		
		
	private static void method2() {
			try {
				int a=3/0;
				System.out.println(a);
			}
			finally {
				System.out.println("Ignore Exception");
			}
			
			
			
		}
		
public static void main(String[] args) {
	
	//method1();
	method2();
	
}
}

